parameters:
  name: "" # defaults for any parameters that aren't specified
  vmImage: ""
  toxenv: ""

jobs:
  - job: ${{ parameters.name }}
    pool:
      vmImage: ${{ parameters.vmImage }}

    strategy:
      matrix:
        Python313:
          python.version: "3.13"

    steps:
      - task: UsePythonVersion@0.206.0
        inputs:
          versionSpec: "$(python.version)"
          architecture: "x64"

      - script: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade tox
        displayName: "Install dependencies"

      - script: "tox -e ${{ parameters.toxenv }}"
        displayName: "Lint"
