name-template: "$NEXT_PATCH_VERSION"
tag-template: "$NEXT_PATCH_VERSION"

categories:
  - title: "Added"
    labels:
      - "Added"
      - "enhancement"
  - title: "Changed"
    label: "Changed"
  - title: "Deprecated"
    label: "Deprecated"
  - title: "Removed"
    label: "Removed"
  - title: "Fixed"
    labels:
      - "Fixed"
      - "bug"
  - title: "Security"
    label: "Security"

exclude-labels:
  - "skip-changelog"

template: |
  ## Changes

  $CHANGES
